[package]
name = "web_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\

[dependencies]
bevy = { path = "../andrew-bevy", version = "0.10.0" }

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
