[package]
name = "web_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html\

[dependencies]

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!

[dependencies.bevy]
version = "0.8"